USE Master
GO

CREATE LOGIN Danielle WITH PASSWORD=N'Pa$$w0rd' MUST_CHANGE, DEFAULT_DATABASE=Chapter8, CHECK_EXPIRATION=ON, CHECK_POLICY=ON ;
GO

USE Chapter7
GO

CREATE USER Danielle FOR LOGIN Danielle ;
GO

USE Chapter8
GO

CREATE USER Danielle FOR LOGIN Danielle ;
GO
