CREATE TRIGGER PreventLoginDuringETL
ON ALL SERVER
FOR LOGON
AS
BEGIN
	IF (CAST(GETDATE() AS TIME) >= CAST('20:00:00' AS TIME) 
		AND CAST(GETDATE() AS TIME) <= CAST('23:00:00' AS TIME) 
		AND UPPER(ORIGINAL_LOGIN()) <> 'ETLSVCACC')
	ROLLBACK ;
END
