USE Chapter24
GO

CREATE TRIGGER DDLAudit
ON DATABASE
WITH EXECUTE AS SELF
AFTER CREATE_PROCEDURE, CREATE_FUNCTION, CREATE_TRIGGER, CREATE_ASSEMBLY, CREATE_TYPE, CREATE_RULE, CREATE_DEFAULT, CREATE_PLAN_GUIDE, CREATE_SEQUENCE, ALTER_PROCEDURE, ALTER_FUNCTION, ALTER_TRIGGER, ALTER_ASSEMBLY, ALTER_PLAN_GUIDE, ALTER_SEQUENCE, DROP_PROCEDURE, DROP_FUNCTION, DROP_TRIGGER, DROP_ASSEMBLY, DROP_TYPE, DROP_RULE, DROP_DEFAULT, DROP_PLAN_GUIDE, DROP_SEQUENCE
AS
BEGIN
	INSERT INTO dbo.Audit
	SELECT EVENTDATA().value('(/EVENT_INSTANCE/PostTime)[1]','datetime2'),
	       EVENTDATA().value('(/EVENT_INSTANCE/LoginName)[1]','nvarchar(128)'),
	       EVENTDATA().value('(/EVENT_INSTANCE/DatabaseName)[1]','nvarchar(128)'),
	       EVENTDATA().value('(/EVENT_INSTANCE/EventType)[1]','nvarchar(128)'),
	       EVENTDATA().value('(/EVENT_INSTANCE/SchemaName)[1]','nvarchar(128)'),
	       EVENTDATA().value('(/EVENT_INSTANCE/ObjectName)[1]','nvarchar(128)'),
	       EVENTDATA().value('(/EVENT_INSTANCE/TSQLCommand/CommandText)[1]','nvarchar(max)') ;
END
