USE Chapter24
GO

CREATE TABLE dbo.Audit
(
ID			INT		IDENTITY	PRIMARY KEY,
PostTime		DATETIME2	NOT NULL,
LoginName		NVARCHAR(128)	NOT NULL,
DatabaseName		NVARCHAR(128)	NOT NULL,
EventType		NVARCHAR(128)	NOT NULL,
SchemaName		NVARCHAR(128)	NULL,
ObjectName		NVARCHAR(128)	NOT NULL,
CommandText		NVARCHAR(MAX)	NOT NULL
) ;
