ALTER DATABASE [Chapter5] ADD FILEGROUP [Chapter5_InMemory] CONTAINS MEMORY_OPTIMIZED_DATA; 
GO

ALTER DATABASE [Chapter5] ADD FILE ( NAME = N'InMemory', FILENAME = N'F:\MSSQL\MSSQL12.PROSQLADMIN\MSSQL\DATA\InMemory' ) TO FILEGROUP [Chapter5_InMemory];
GO  
