DBCC FREEPROCCACHE
DBCC DROPCLEANBUFFERS

SET STATISTICS TIME ON
SET STATISTICS IO ON

SELECT OrderNumber
FROM OrdersMemHash
WHERE OrderNumber  BETWEEN 78 AND 98

SELECT OrderNumber
FROM OrdersMemNonClust
WHERE OrderNumber BETWEEN 78 AND 98

SELECT OrderNumber
FROM OrdersDisc
WHERE OrderNumber  BETWEEN 78 AND 98
