CREATE DATABASE Chapter16MmemOpt_Sub 
ON PRIMARY ( NAME = [PRIMARY], FILENAME = [C:\MSSQL\DATA\Chapter16MemOpt_Sub.mdf]), 
FILEGROUP [MemoryOptimized] CONTAINS MEMORY_OPTIMIZED_DATA ( NAME = [MemoryOptimized], FILENAME = [C:\MSSQL\DATA\Sub])
LOG ON ( NAME = [Chapter16MemOpt_Sub_Log], FILENAME = [C:\MSSQL\LOG\Sub.ldf])
COLLATE Latin1_General_CS_AS_KS_WS;

ALTER DATABASE Chapter16MmemOpt_Sub SET MEMORY_OPTIMIZED_ELEVATE_TO_SNAPSHOT = ON;
GO

USE Chapter16MemOpt_Sub
GO

CREATE TABLE [dbo].[Customers](
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL PRIMARY KEY NONCLUSTERED HASH WITH (BUCKET_COUNT = 2000),
	[FirstName] [nvarchar](30) COLLATE Latin1_General_BIN2 NULL,
	[LastName] [nvarchar](30) COLLATE Latin1_General_BIN2 NULL
) WITH (MEMORY_OPTIMIZED = ON, DURABILITY = SCHEMA_AND_DATA) ;
