--Configure the ASYNCDR Replica to allow read-only connections

ALTER AVAILABILITY GROUP App1
 MODIFY REPLICA ON N'CLUSTERNODE3\ASYNCDR' WITH 
(SECONDARY_ROLE (ALLOW_CONNECTIONS = READ_ONLY)) ;

--Configure the read-only URL for the ASYNCDR Replica

ALTER AVAILABILITY GROUP App1
 MODIFY REPLICA ON N'CLUSTERNODE3\ASYNCDR' WITH 
(SECONDARY_ROLE (READ_ONLY_ROUTING_URL = N'TCP://CLUSTERNODE3.PROSQLADMIN.com:1433')) ;

--Configure the read-only routing list on the Primary Replica

ALTER AVAILABILITY GROUP App1 
MODIFY REPLICA ON N'CLUSTERNODE1\PRIMARYREPLICA' WITH 
(PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=('CLUSTERNODE3\ASYNCDR'))) ;
